apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-templates
  namespace: monitoring
data:
  slack.tmpl: |
    {{ define "slack.default.title" }}
    [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}{{ if eq .Status "resolved" }}:{{ .Alerts.Resolved | len }}{{ end }}] {{ .GroupLabels.alertname }}
    {{ end }}
    
    {{ define "slack.default.text" }}
    {{ range .Alerts }}
    *Alert:* {{ .Annotations.summary }}
    *Description:* {{ .Annotations.description }}
    *Severity:* {{ .Labels.severity }}
    *Service:* {{ .Labels.service }}
    *Instance:* {{ .Labels.instance }}
    *Started:* {{ .StartsAt | since }}
    {{ if .EndsAt }}*Ended:* {{ .EndsAt | since }}{{ end }}
    {{ end }}
    {{ end }}
    
    {{ define "slack.default.footer" }}
    {{ .CommonAnnotations.summary }}
    {{ end }}
    
    {{ define "slack.default.color" }}
    {{ if eq .Status "firing" }}danger{{ else }}good{{ end }}
    {{ end }}

  pagerduty.tmpl: |
    {{ define "pagerduty.default.description" }}
    [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}{{ if eq .Status "resolved" }}:{{ .Alerts.Resolved | len }}{{ end }}] {{ .GroupLabels.alertname }}
    {{ end }}
    
    {{ define "pagerduty.default.clientURL" }}
    {{ template "pagerduty.default.grafanaURL" . }}
    {{ end }}
    
    {{ define "pagerduty.default.grafanaURL" }}
    {{ $grafanaURL := "http://grafana:3000" }}
    {{ $grafanaURL }}/d/{{ .CommonAnnotations.grafana_dashboard }}
    {{ end }}
    
    {{ define "pagerduty.default.severity" }}
    {{ if eq .CommonLabels.severity "critical" }}critical{{ else }}warning{{ end }}
    {{ end }}

  email.tmpl: |
    {{ define "email.default.subject" }}
    [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}{{ if eq .Status "resolved" }}:{{ .Alerts.Resolved | len }}{{ end }}] {{ .GroupLabels.alertname }}
    {{ end }}
    
    {{ define "email.default.html" }}
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>{{ template "email.default.subject" . }}</title>
    </head>
    <body>
        <h1>{{ template "email.default.subject" . }}</h1>
        <p><strong>Status:</strong> {{ .Status | toUpper }}</p>
        <p><strong>Group:</strong> {{ .GroupLabels.alertname }}</p>
        <p><strong>Service:</strong> {{ .CommonLabels.service }}</p>
        
        {{ if .Alerts }}
        <h2>Alerts:</h2>
        <ul>
        {{ range .Alerts }}
            <li>
                <strong>{{ .Annotations.summary }}</strong><br>
                {{ .Annotations.description }}<br>
                <strong>Severity:</strong> {{ .Labels.severity }}<br>
                <strong>Instance:</strong> {{ .Labels.instance }}<br>
                <strong>Started:</strong> {{ .StartsAt | since }}<br>
                {{ if .EndsAt }}<strong>Ended:</strong> {{ .EndsAt | since }}<br>{{ end }}
            </li>
        {{ end }}
        </ul>
        {{ end }}
        
        <p><strong>Summary:</strong> {{ .CommonAnnotations.summary }}</p>
    </body>
    </html>
    {{ end }} 