apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config-enhanced
  namespace: monitoring
data:
  loki.yaml: |
    auth_enabled: false
    
    server:
      http_listen_port: 3100
      grpc_listen_port: 9096
    
    common:
      path_prefix: /var/loki
      storage:
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory
    
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    
    ruler:
      alertmanager_url: http://alertmanager:9093
    
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m
      split_queries_by_interval: 15m
      max_query_parallelism: 32
      max_streams_per_user: 0
      max_global_streams_per_user: 0
      ingestion_rate_mb: 32
      ingestion_burst_size_mb: 64
      max_entries_limit_per_query: 5000
      max_query_series: 500
      max_query_lookback: 168h
      max_query_length: 721h
      max_query_parallelism: 32
      cardinality_limit: 100000
      max_streams_matchers_per_query: 1000
      max_concurrent_tail_requests: 10
      max_entries_limit_per_query: 5000
      max_cache_freshness_per_query: 1m
      max_queriers_per_tenant: 10
      max_query_parallelism: 32
      max_streams_per_user: 0
      max_global_streams_per_user: 0
      ingestion_rate_mb: 32
      ingestion_burst_size_mb: 64
      per_stream_rate_limit: 3MB
      per_stream_rate_limit_burst: 15MB
    
    chunk_store_config:
      max_look_back_period: 0s
    
    table_manager:
      retention_deletes_enabled: true
      retention_period: 744h
    
    query_range:
      align_queries_with_step: true
      max_retries: 5
      split_queries_by_interval: 15m
      cache_results: true
      results_cache:
        cache:
          enable_fifocache: true
          fifocache:
            max_size_bytes: 500MB
            validity: 24h
    
    frontend:
      compress_responses: true
      log_queries_longer_than: 5s
      downstream_url: http://loki:3100
      parallelise_shardable_queries: true 