apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-config
  namespace: monitoring
data:
  mimir.yaml: |
    multitenancy_enabled: false
    
    server:
      http_listen_port: 9009
      grpc_listen_port: 9095
    
    distributor:
      ring:
        kvstore:
          store: memberlist
    
    ingester:
      ring:
        kvstore:
          store: memberlist
        heartbeat_timeout: 1m
        heartbeat_period: 10s
    
    compactor:
      sharding_ring:
        kvstore:
          store: memberlist
    
    store_gateway:
      sharding_ring:
        kvstore:
          store: memberlist
    
    ruler:
      ring:
        kvstore:
          store: memberlist
    
    alertmanager:
      sharding_ring:
        kvstore:
          store: memberlist
    
    limits:
      max_global_series_per_user: 1000000
      max_global_series_per_metric: 100000
      ingestion_rate: 10000
      ingestion_burst_size: 20000
      max_global_exemplars_per_user: 10000
      max_global_metadata_per_user: 10000
      max_global_metadata_per_metric: 10000
      ruler_max_rules_per_rule_group: 20
      ruler_max_rule_groups_per_tenant: 70
    
    memberlist:
      join_members:
        - mimir:7946 