apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-config
  namespace: monitoring
data:
  mimir.yaml: |
    multitenancy_enabled: false
    
    server:
      http_listen_port: 9009
      grpc_listen_port: 9095
    
    distributor:
      ring:
        kvstore:
          store: memberlist
        replication_factor: 1
    
    ingester:
      ring:
        kvstore:
          store: memberlist
        replication_factor: 1
        heartbeat_timeout: 1m
        heartbeat_period: 10s
      max_global_series_per_user: 1000000
      max_global_series_per_metric: 100000
    
    compactor:
      sharding_ring:
        kvstore:
          store: memberlist
        replication_factor: 1
    
    store_gateway:
      sharding_ring:
        kvstore:
          store: memberlist
        replication_factor: 1
    
    ruler:
      ring:
        kvstore:
          store: memberlist
        replication_factor: 1
    
    alertmanager:
      sharding_ring:
        kvstore:
          store: memberlist
        replication_factor: 1
    
    memberlist:
      join_members:
        - mimir:7946
    
    limits:
      max_global_series_per_user: 1000000
      max_global_series_per_metric: 100000
      ingestion_rate: 10000
      ingestion_burst_size: 20000
      max_global_exemplars_per_user: 10000
      max_global_metadata_per_user: 10000
      max_global_metadata_per_metric: 10000
      ruler_max_rules_per_rule_group: 20
      ruler_max_rule_groups_per_tenant: 70
    
    storage:
      engine: blocks
      blocks_storage:
        backend: filesystem
        filesystem:
          dir: /data/mimir/blocks
        tsdb:
          dir: /data/mimir/tsdb
        bucket_store:
          sync_dir: /data/mimir/bucket-sync
          index_cache:
            backend: filesystem
            filesystem:
              dir: /data/mimir/index-cache
        compactor:
          data_dir: /data/mimir/compactor
          sharding_ring:
            kvstore:
              store: memberlist
            replication_factor: 1
    
    common:
      storage:
        backend: filesystem
        filesystem:
          dir: /data/mimir/rules 