apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: monitoring
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      jaeger:
        protocols:
          grpc:
            endpoint: 0.0.0.0:14250
          thrift_http:
            endpoint: 0.0.0.0:14268
          thrift_binary:
            endpoint: 0.0.0.0:6832
          thrift_compact:
            endpoint: 0.0.0.0:6831
      zipkin:
        endpoint: 0.0.0.0:9411
    
    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
      memory_limiter:
        check_interval: 1s
        limit_mib: 1500
      resource:
        attributes:
          - key: environment
            value: "production"
            action: upsert
          - key: service.version
            from_attribute: "service.version"
            action: upsert
    
    exporters:
      otlp/tempo:
        endpoint: tempo:4317
        tls:
          insecure: true
      logging:
        loglevel: debug
      prometheus:
        endpoint: 0.0.0.0:9464
        namespace: "otel"
        const_labels:
          label1: value1
        send_timestamps: true
        metric_expiration: 180m
        enable_open_metrics: true
    
    service:
      pipelines:
        traces:
          receivers: [otlp, jaeger, zipkin]
          processors: [batch, memory_limiter, resource]
          exporters: [otlp/tempo, logging]
        metrics:
          receivers: [otlp]
          processors: [batch, memory_limiter, resource]
          exporters: [prometheus, logging]
        logs:
          receivers: [otlp]
          processors: [batch, memory_limiter, resource]
          exporters: [logging] 