apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    
    positions:
      filename: /tmp/positions.yaml
    
    clients:
      - url: http://loki:3100/loki/api/v1/push
    
    scrape_configs:
      - job_name: kubernetes-pods-name
        kubernetes_sd_configs:
          - role: pod
        pipeline_stages:
          - docker: {}
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_label_app
            target_label: app
          - source_labels:
              - __meta_kubernetes_pod_label_component
            target_label: component
          - source_labels:
              - __meta_kubernetes_namespace_name
            target_label: namespace
          - source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
          - source_labels:
              - __meta_kubernetes_pod_uid
            target_label: pod_uid
          - source_labels:
              - __meta_kubernetes_pod_annotation_kubernetes_io_hostname
            target_label: node
          - action: replace
            replacement: $1
            separator: /
            source_labels:
              - namespace
              - pod
            target_label: job
          - action: replace
            source_labels:
              - __meta_kubernetes_namespace_name
            target_label: namespace
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
          - replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
            target_label: __path__
      
      - job_name: kubernetes-pods-app
        kubernetes_sd_configs:
          - role: pod
        pipeline_stages:
          - docker: {}
        relabel_configs:
          - action: drop
            regex: .+
            source_labels:
              - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_label_app
            target_label: app
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_label_component
            target_label: component
          - action: replace
            source_labels:
              - __meta_kubernetes_namespace_name
            target_label: namespace
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_uid
            target_label: pod_uid
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_annotation_kubernetes_io_hostname
            target_label: node
          - action: replace
            replacement: $1
            separator: /
            source_labels:
              - namespace
              - pod
            target_label: job
          - action: replace
            source_labels:
              - __meta_kubernetes_namespace_name
            target_label: namespace
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
          - replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
            target_label: __path__
      
      - job_name: kubernetes-pods-direct-controllers
        kubernetes_sd_configs:
          - role: pod
        pipeline_stages:
          - docker: {}
        relabel_configs:
          - action: drop
            regex: .+
            source_labels:
              - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
          - action: drop
            regex: .+
            source_labels:
              - __meta_kubernetes_pod_label_app
          - action: drop
            regex: .+
            source_labels:
              - __meta_kubernetes_pod_label_component
          - action: replace
            source_labels:
              - __meta_kubernetes_namespace_name
            target_label: namespace
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_uid
            target_label: pod_uid
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_annotation_kubernetes_io_hostname
            target_label: node
          - action: replace
            replacement: $1
            separator: /
            source_labels:
              - namespace
              - pod
            target_label: job
          - action: replace
            source_labels:
              - __meta_kubernetes_namespace_name
            target_label: namespace
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
          - replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
            target_label: __path__
      
      - job_name: kubernetes-pods-indirect-controller
        kubernetes_sd_configs:
          - role: pod
        pipeline_stages:
          - docker: {}
        relabel_configs:
          - action: drop
            regex: .+
            source_labels:
              - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
          - action: keep
            regex: .+
            source_labels:
              - __meta_kubernetes_pod_label_app
          - action: drop
            regex: .+
            source_labels:
              - __meta_kubernetes_pod_label_component
          - action: replace
            source_labels:
              - __meta_kubernetes_namespace_name
            target_label: namespace
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_uid
            target_label: pod_uid
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_annotation_kubernetes_io_hostname
            target_label: node
          - action: replace
            replacement: $1
            separator: /
            source_labels:
              - namespace
              - pod
            target_label: job
          - action: replace
            source_labels:
              - __meta_kubernetes_namespace_name
            target_label: namespace
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
          - replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
            target_label: __path__
      
      - job_name: kubernetes-pods-static
        kubernetes_sd_configs:
          - role: pod
        pipeline_stages:
          - docker: {}
        relabel_configs:
          - action: drop
            regex: .+
            source_labels:
              - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
          - action: replace
            source_labels:
              - __meta_kubernetes_namespace_name
            target_label: namespace
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_uid
            target_label: pod_uid
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_annotation_kubernetes_io_hostname
            target_label: node
          - action: replace
            replacement: $1
            separator: /
            source_labels:
              - namespace
              - pod
            target_label: job
          - action: replace
            source_labels:
              - __meta_kubernetes_namespace_name
            target_label: namespace
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
          - replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
            target_label: __path__ 