apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: monitoring
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200
      grpc_listen_port: 9095
    
    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces
        wal:
          path: /var/tempo/wal
        pool:
          max_workers: 100
          queue_depth: 10000
    
    metrics_generator:
      registry:
        external_labels:
          source: tempo
          cluster: ecommerce-01-cluster
      storage:
        path: /var/tempo/generator/wal
        remote_write:
          - url: http://mimir:9009/api/v1/push
            send_exemplars: true
    
    compactor:
      compaction:
        block_retention: 1h
        compacted_block_retention: 10m
      storage:
        path: /var/tempo/compactor
        trace:
          backend: local
          local:
            path: /var/tempo/traces
    
    distributor:
      receivers:
        jaeger:
          protocols:
            thrift_http:
              endpoint: "0.0.0.0:14268"
            grpc:
              endpoint: "0.0.0.0:14250"
            thrift_binary:
              endpoint: "0.0.0.0:6832"
            thrift_compact:
              endpoint: "0.0.0.0:6831"
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317"
            http:
              endpoint: "0.0.0.0:4318"
        zipkin:
          endpoint: "0.0.0.0:9411"
    
    ingester:
      max_block_bytes: 1_000_000
      max_block_duration: 5m
      max_compaction_objects: 6000000
      complete_block_timeout: 1h
      retention: 24h
    
    querier:
      frontend_worker:
        frontend_address: "tempo-query-frontend:9095"
    
    query_frontend:
      downstream_url: "http://tempo-querier:3200"
    
    memberlist:
      join_members:
        - tempo:7946 