apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector
  namespace: monitoring
  labels:
    app: vector
    component: logging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vector
  template:
    metadata:
      labels:
        app: vector
        component: logging
    spec:
      serviceAccountName: vector
      containers:
      - name: vector
        image: timberio/vector:0.34-alpine
        ports:
        - containerPort: 8686
          name: api
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 4Gi
        volumeMounts:
        - name: vector-config
          mountPath: /etc/vector/vector.yaml
          subPath: vector.yaml
        - name: var-log
          mountPath: /var/log
          readOnly: true
        - name: var-lib
          mountPath: /var/lib
          readOnly: true
        - name: etc-machine-id
          mountPath: /etc/machine-id
          readOnly: true
        livenessProbe:
          httpGet:
            path: /health
            port: 8686
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8686
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: vector-config
        configMap:
          name: vector-config
      - name: var-log
        hostPath:
          path: /var/log
      - name: var-lib
        hostPath:
          path: /var/lib
      - name: etc-machine-id
        hostPath:
          path: /etc/machine-id
---
apiVersion: v1
kind: Service
metadata:
  name: vector
  namespace: monitoring
  labels:
    app: vector
    component: logging
spec:
  ports:
  - port: 8686
    targetPort: 8686
    name: api
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: vector
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vector
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vector
subjects:
- kind: ServiceAccount
  name: vector
  namespace: monitoring 