apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
  namespace: monitoring
data:
  vector.yaml: |
    api:
      enabled: true
      address: "0.0.0.0:8686"
    
    sources:
      # Container logs from Kubernetes
      container_logs:
        type: "kubernetes_logs"
        glob_minimum_cooldown_ms: 1000
        self_node_name: "${NODE_NAME}"
        exclude_paths_glob_patterns:
          - "/var/log/containers/vector-*.log"
          - "/var/log/containers/kube-system-*.log"
    
    transforms:
      # Add Kubernetes metadata
      add_k8s_metadata:
        type: "remap"
        inputs: ["container_logs"]
        source: |
          if exists(.kubernetes) {
            .namespace = .kubernetes.namespace_name
            .pod_name = .kubernetes.pod_name
            .container_name = .kubernetes.container_name
          }
    
    sinks:
      # Console output for debugging
      console:
        type: "console"
        inputs: ["add_k8s_metadata"]
        encoding:
          codec: "json"
        target: "stdout" 