# AWS-Optimized Kubernetes Manifests for microservices-demo
# This file contains AWS-specific optimizations for the Online Boutique application

# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: ecomm-prod
  labels:
    app.kubernetes.io/name: ecomm-prod
    app.kubernetes.io/instance: ecomm-prod
---
# Frontend Service with AWS LoadBalancer optimizations
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
  namespace: ecomm-prod
  labels:
    app: frontend
  annotations:
    # AWS-specific Load Balancer annotations
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/_healthz"
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
---
# ConfigMap for AWS-specific configurations
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-config
  namespace: ecomm-prod
data:
  ENV_PLATFORM: "aws"
  ENABLE_PROFILER: "0"
  # Add any other AWS-specific configurations here 